apiVersion: v1
kind: Service
metadata:
  name: monolith-to-microservices-user
  labels:
    app: monolith-to-microservices-user
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: monolith-to-microservices-user